[book]
title = "凹库凹库"
authors = ["凹语言社区"]
description = "凹语言资料库"
language = "zh"
multilingual = false
src = "."

[output.html.fold]
enable = true
level = 0

[output.html]
git-repository-url = "https://github.com/wa-lang/waku"
edit-url-template = "https://github.com/wa-lang/waku/edit/master/{path}"
git-repository-icon = "fa-github"
